force-app/main/default/objects/uu_Changelog_Item__c/uu_Changelog_Item__c.object-meta.xml
<CustomObject>
    <label>Changelog Item</label>
    <nameField>
        <displayFormat>CLI-{0000000000}</displayFormat>
        <label>Salesforce Changelog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Changelog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uu_Changelog_Item__c/fields/Change_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Change_Datetime__c</fullName>
    <label>Change Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/uu_Changelog_Item__c/fields/Change_Type__c.field-meta.xml
<CustomField>
    <fullName>Change_Type__c</fullName>
    <label>Change Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ascend Release</fullName>
            </value>
            <value>
                <fullName>Bug Fix</fullName>
            </value>
            <value>
                <fullName>Feature Update</fullName>
            </value>
            <value>
                <fullName>New Feature</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Salesforce Release</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/uu_Changelog_Item__c/fields/Documentation_Link__c.field-meta.xml
<CustomField>
    <fullName>Documentation_Link__c</fullName>
    <label>Documentation Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/uu_Changelog_Item__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/uu_Changelog_Item__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uu_Changelog_Setting__mdt/uu_Changelog_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Changelog Setting</label>
    <pluralLabel>Changelog Settings</pluralLabel>
</CustomObject>

force-app/main/default/classes/ChangelogItem.cls
/**
 * @description abstracts uu_Changelog_Item__c records
 *
 * @author Ben Repak 20231030
 *
 * Modification Log:
 *
 * MOD      DATE        AUTHOR          MODIFICATION
 *
*/

public with sharing class ChangelogItem{
    public String changelogId;
    public String changelogTitle;
    public String changelogDocumentLink;
    public String changelogShortDescription;
    public Date changelogDate;
    public String changeType;
    public String iconType;

    /**
     * @description  constructor to dynamically build changelog item based on the provided setting
     * @param item changelog record to be abstracted
     * @param changelogSetting instance of ChangelogSetting (abstracted uu_Changelog_Setting__mdt)
     */
    public ChangelogItem(uu_Changelog_Item__c item, ChangelogSetting changelogSetting){
        this.changelogDate = Date.valueOf(item.Change_Datetime__c);
        this.changelogId = item.Id;
        this.changelogTitle = item.Title__c;
        this.changelogShortDescription = item.Short_Description__c;
        this.changelogDocumentLink = item.Documentation_Link__c;
        this.changeType = item.Change_Type__c;

        // conditionally set icon type
        if(String.isNotBlank(item.Change_Type__c)) {
            if(changelogSetting.settingTypeIconMap.containsKey(item.Change_Type__c)){
                this.iconType = changelogSetting.settingTypeIconMap.get(item.Change_Type__c);
            } else {
                this.iconType = changelogSetting.settingDefaultItemIcon;
            }
        }
    }
}