force-app/main/default/objects/uu_Changelog_Setting__mdt/uu_Changelog_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Changelog Setting</label>
    <pluralLabel>Changelog Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/uu_Changelog_Setting__mdt/fields/Change_Item_Icon_Default__c.field-meta.xml
<CustomField>
    <fullName>Change_Item_Icon_Default__c</fullName>
    <defaultValue>&quot;action:approval&quot;</defaultValue>
    <label>Change Item Icon Default</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uu_Changelog_Setting__mdt/fields/Change_Type_Icon_Map__c.field-meta.xml
<CustomField>
    <fullName>Change_Type_Icon_Map__c</fullName>
    <description>Maps lightning-icons to Change Type field. Defaults to action:approval.</description>
    <label>Change Type Icon Map</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/uu_Changelog_Setting__mdt/fields/Changelog_Modal_Body__c.field-meta.xml
<CustomField>
    <fullName>Changelog_Modal_Body__c</fullName>
    <label>Changelog Modal Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uu_Changelog_Setting__mdt/fields/Changelog_Modal_Header__c.field-meta.xml
<CustomField>
    <fullName>Changelog_Modal_Header__c</fullName>
    <label>Changelog Modal Header</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uu_Changelog_Setting__mdt/fields/Component_Title__c.field-meta.xml
<CustomField>
    <fullName>Component_Title__c</fullName>
    <label>Component Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uu_Changelog_Setting__mdt/fields/Filter_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Filter_Criteria__c</fullName>
    <defaultValue>&quot;Is_Published__c = &apos;Yes&apos; AND Change_Datetime__c = LAST_N_DAYS:30&quot;</defaultValue>
    <description>The filter criteria supports the WHERE clause specified at https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_conditionexpression.htm.</description>
    <inlineHelpText>The filter criteria supports the WHERE clause specified at https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_conditionexpression.htm.</inlineHelpText>
    <label>Filter Criteria</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/uu_Changelog_Setting__mdt/fields/New_Items_Icon__c.field-meta.xml
<CustomField>
    <fullName>New_Items_Icon__c</fullName>
    <defaultValue>&quot;utility:settings&quot;</defaultValue>
    <label>New Items Icon</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uu_Changelog_Setting__mdt/fields/New_Items_Message__c.field-meta.xml
<CustomField>
    <fullName>New_Items_Message__c</fullName>
    <description>Displayed when changelog items were published since the user&apos;s last view</description>
    <inlineHelpText>Displayed when changelog items were published since the user&apos;s last view</inlineHelpText>
    <label>New Items Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uu_Changelog_Setting__mdt/fields/Read_Items_Message__c.field-meta.xml
<CustomField>
    <fullName>Read_Items_Message__c</fullName>
    <description>Displayed when no new changelog items were published since the user&apos;s last view</description>
    <inlineHelpText>Displayed when no new changelog items were published since the user&apos;s last view</inlineHelpText>
    <label>Read Items Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChangelogSetting.cls
/**
 * @description abstracts uu_Changelog_Setting__mdt
 *
 * @author Ben Repak 20231030
 *
 * Modification Log:
 *
 * MOD      DATE        AUTHOR          MODIFICATION
 *
*/

public with sharing class ChangelogSetting{

    public String settingName;
    public String settingNewItemsMessage;
    public String settingReadItemsMessage;
    public String settingComponentTitle;
    public String settingNewItemsIcon;
    public String settingModalBody;
    public String settingModalHeader;
    public String settingDefaultItemIcon;
    public String filterCriteria;
    public Map<String,String> settingTypeIconMap;

    /**
     * @description  constructor to abstract uu_Changelog_Setting__mdt into a custom apex class
     * @param setting a single uu_Changelog_Setting__mdt record for the given implementation of changelog
     */
    public ChangelogSetting(uu_Changelog_Setting__mdt setting){
        this.settingName = setting.DeveloperName;
        this.settingComponentTitle = setting.Component_Title__c.trim();
        this.settingNewItemsIcon = setting.New_Items_Icon__c.trim();
        this.settingNewItemsMessage = setting.New_Items_Message__c.trim();
        this.settingReadItemsMessage = setting.Read_Items_Message__c.trim();
        this.settingModalHeader = setting.Changelog_Modal_Header__c.trim();
        this.settingModalBody = setting.Changelog_Modal_Body__c;
        this.settingDefaultItemIcon = setting.Change_Item_Icon_Default__c.trim();
        this.settingTypeIconMap = new Map<String, String>();
        this.filterCriteria = setting.Filter_Criteria__c.trim().normalizeSpace();

        // dynamically set icon type based on custom metadata settings
        if(String.isNotBlank(setting.Change_Type_Icon_Map__c)){
            String iconMapString = setting.Change_Type_Icon_Map__c.normalizeSpace();
            Map<String, Object> settings = (Map<String, Object>)JSON.deserializeUntyped(iconMapString);
            for(String s : settings.keySet()){
                settingTypeIconMap.put(s, (String)settings.get(s));
            }
        }
    }


}